"use client";

import * as React from "react";
import { CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import {
	type ChartConfig,
	ChartContainer,
	ChartTooltip,
	ChartTooltipContent,
} from "@/components/ui/chart";

const chartData = [
	{ month: "Jan", website: 45, referral: 28, social: 32 },
	{ month: "Feb", website: 52, referral: 35, social: 38 },
	{ month: "Mar", website: 48, referral: 30, social: 35 },
	{ month: "Apr", website: 61, referral: 42, social: 45 },
	{ month: "May", website: 55, referral: 38, social: 40 },
	{ month: "Jun", website: 67, referral: 45, social: 52 },
	{ month: "Jul", website: 72, referral: 50, social: 58 },
	{ month: "Aug", website: 65, referral: 43, social: 48 },
	{ month: "Sep", website: 78, referral: 55, social: 62 },
	{ month: "Oct", website: 82, referral: 58, social: 65 },
	{ month: "Nov", website: 75, referral: 52, social: 58 },
	{ month: "Dec", website: 88, referral: 62, social: 72 },
];

const chartConfig = {
	website: {
		label: "Website",
		color: "hsl(var(--chart-1))",
	},
	referral: {
		label: "Referral",
		color: "hsl(var(--chart-2))",
	},
	social: {
		label: "Social Media",
		color: "hsl(var(--chart-3))",
	},
} satisfies ChartConfig;

export function CRMLeadsBySourceChart() {
	return (
		<Card>
			<CardHeader>
				<CardTitle>Leads by Source</CardTitle>
				<CardDescription>Monthly leads generated by source</CardDescription>
			</CardHeader>
			<CardContent>
				<ChartContainer config={chartConfig}>
					<LineChart
						accessibilityLayer
						data={chartData}
						margin={{
							left: 12,
							right: 12,
						}}
					>
						<CartesianGrid vertical={false} />
						<XAxis
							dataKey="month"
							tickLine={false}
							axisLine={false}
							tickMargin={8}
						/>
						<YAxis tickLine={false} axisLine={false} tickMargin={8} />
						<ChartTooltip
							cursor={false}
							content={<ChartTooltipContent indicator="line" />}
						/>
						<Line
							type="monotone"
							dataKey="website"
							stroke="var(--color-website)"
							strokeWidth={2}
							dot={false}
						/>
						<Line
							type="monotone"
							dataKey="referral"
							stroke="var(--color-referral)"
							strokeWidth={2}
							dot={false}
						/>
						<Line
							type="monotone"
							dataKey="social"
							stroke="var(--color-social)"
							strokeWidth={2}
							dot={false}
						/>
					</LineChart>
				</ChartContainer>
			</CardContent>
		</Card>
	);
}
