FROM oven/bun:1.1.38-debian AS builder
WORKDIR /workspace
ENV BUN_NO_TELEMETRY=1
ENV NEXT_TELEMETRY_DISABLED=1
COPY . .
RUN bun install --frozen-lockfile
RUN bun run --filter ./apps/dashboard build
RUN cd apps/dashboard && bun install --frozen-lockfile --production

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=builder /workspace/apps/dashboard /app
EXPOSE 3000
CMD ["npm", "run", "start"]

