apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: crm-monorepo-pipeline-run
spec:
  pipelineRef:
    name: crm-monorepo-pipeline
  serviceAccountName: pipeline-priv
  taskRunTemplate:
    serviceAccountName: pipeline-priv
  taskRunSpecs:
    - pipelineTaskName: build-api
      serviceAccountName: pipeline-priv
    - pipelineTaskName: build-dashboard
      serviceAccountName: pipeline-priv
  params:
    - name: git-repo-url
      value: https://github.com/darioristic/collector-v.0.1.git
    - name: git-revision
      value: main
    - name: registry
      value: image-registry.openshift-image-registry.svc:5000
    - name: namespace
      value: crm-platform-prod
    - name: image-tag
      value: latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: crm-monorepo-workspace
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
