apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: api
  labels:
    app: api
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  lookupPolicy:
    local: true

