apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
    deploymentconfig: notification-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
      protocol: TCP

